script: added benchmark scripts
artipie/benchmarks pull request #32
Opened 2021-07-12 14:00 UTC by g4s8

For #31 - Added `Makefile` to run benchmarks, created util `generate.py` to
generate benchmark scripts based on benchmrak configuration
(`benchmarks.json`), added README.

2021-07-12 14:57 UTC, olenagerasimova approved these changes, later dismissed
@g4s8 thanks, I'd like to notice though that as we are downloading and unpacking test data as `tar.gz` we have to use this archive types for all other data in the future. Maybe, we should at least to document it somewhere?

2021-07-12 21:01 UTC, genryxy requested changes
@g4s8 thanks, please check comments

2021-07-12 21:01 UTC, genryxy commented on adapters/benchmarks.json
> +                                        "args": [],
@g4s8 why here class is not `org.openjdk.jmh.Main` and no args are passed

2021-07-12 21:01 UTC, genryxy commented on adapters/benchmarks.json
> +                                        "data": "https://artipie.s3.amazonaws.com/helm-test/helm100.tar.gz",
@g4s8 it was also mentioned to run benchmarks for larger repository which includes 1000 charts instead of 100. So, probably to pass data as an array or something else?

2021-07-12 21:01 UTC, genryxy commented on adapters/generate.py
> +#!/bin/bash
@g4s8 is it possible to pass a version of adapter which is checked now?

2021-07-12 21:01 UTC, genryxy commented on adapters/README.md
> +This is universal adapter benchmrak toolcit for running different SDK benchmarks from
@g4s8 looks like a typo in `toolcit`

2021-07-13 11:10 UTC, g4s8 commented on adapters/benchmarks.json
> +                                        "data": "https://artipie.s3.amazonaws.com/helm-test/helm100.tar.gz",
This is why the script is auto-generated - for default runs, 1000 charts package is too big, but if somebody wants to run such a benchmark, then it's possible to use another benchmarks JSON and run it from the same Makefile

2021-07-13 11:11 UTC, g4s8 commented on adapters/benchmarks.json
> +                                        "args": [],
JMH allows using different entry points. Rpm adapter was designed where each benchmark is a main class

2021-07-13 11:12 UTC, g4s8 commented
@olenagerasimova @genryxy thanks, added more details about test data format, and fixed some comments

2021-07-13 11:15 UTC, olenagerasimova approved these changes
@g4s8 thanks, looks good to me

2021-07-13 11:24 UTC, genryxy approved these changes
@g4s8 thanks, looks good

2021-07-13 11:31 UTC, merged