feat: add script for writing results to README and checkout ref
artipie/benchmarks pull request #38
Opened 2021-11-15 10:49 UTC by genryxy

Part of artipie/artipie#431
Added script for writing results to README and made checkout by specified ref

2021-11-15 11:00 UTC, olenagerasimova approved these changes, later dismissed
@genryxy thanks, though I'd suggest asking Kirill to review this PR

2021-11-15 11:37 UTC, genryxy commented
@g4s8 could you please take a look

2021-11-15 12:42 UTC, g4s8 commented
@genryxy where this script will add results in README file?

2021-11-15 12:45 UTC, genryxy commented
@g4s8 in [these ](https://github.com/artipie/benchmarks/pull/38/files#diff-66c3d19864f5e0aa28635807694445eb6af1729c963f3364e21972c221a370bdR107-R113) lines new results are added to the README

2021-11-15 12:49 UTC, g4s8 requested changes
@genryxy so what happens if the readme is not ended with benchmarks table? It seems this script will add invalid markdown syntax to the end of readme page in that case

2021-11-15 13:02 UTC, genryxy commented
@g4s8 it will change the content of the file. More precisely, it will move the entire text below the table above the table. If there are several tables in this README file, it won't work correctly

2021-11-15 14:14 UTC, genryxy commented
@g4s8 here some examples

**First (new bench)** 
--
The table below contains info about results of benchmarks for different versions for existed SDK API operations.

| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex |
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |  
| 1.1.1 | 30.448 ± 0.152 | 31.055 ± 0.096 | 5.342 ± 0.011 |

**Result**
--
The table below contains info about results of benchmarks for different versions for existed SDK API operations.

| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex | newBench |
|:---:|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |-|
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |-|  
| 1.1.1 | 30.448 ± 0.152 | 31.055 ± 0.096 | 5.342 ± 0.011 |-|
|new1.1.2|val1|val2|val3|val4|

**Second (old bench did not run)**
--
Some text here.

| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex |
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |  
| 1.1.1 | 30.448 ± 0.152 | 31.055 ± 0.096 | 5.342 ± 0.011 |

**Result**
--
Some text here.

| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex | 
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |
| 1.1.1 | 30.448 ± 0.152 | 31.055 ± 0.096 | 5.342 ± 0.011 |
|new1.1.2|val1|val2|-|

**Third (without table)**
--
Some text here. Here is not any table.

**Result**
--
Some text here. Here is not any table.

| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex | 
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |

**Fourth (text below the table)**
--
Some text here above the table.
| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex | 
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |

**Some text here below the table.**

**Result**
--
Some text here above the table.
**Some text here below the table.**
| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex | 
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |
|new1.1.2|val1|val2|val3|

**Fifth (several tables in README)**
--
Some text here above the table.
| Version | HelmAstoAdd | HelmAstoRemove | HelmAstoReindex | 
|:---:|:---:|:---:|:---:|
| 0.3 | 50.708 ± 0.115 | 51.498 ± 0.165 | 6.858 ± 0.009 |
| 1.0.1 | 50.454 ± 0.111 | 51.308 ± 0.173 | 8.015 ± 0.017 |

|Another|table|
|:---:|:---:|
|it is|unexpected|

**Result**
--
The result will be wrong because also values from the second table will be taken.

2021-11-16 13:48 UTC, g4s8 commented
@genryxy I see, maybe we can update another file specified by user, not README?

2021-11-16 16:06 UTC, genryxy commented
@g4s8 thanks, now it will be written to a separate file `results.md`. And link to this file could be added to the readme file

2021-11-17 09:19 UTC, g4s8 submitted a review, later dismissed
@genryxy thanks

2021-11-17 09:31 UTC, genryxy commented
@g4s8 could you please merge

2021-11-17 19:23 UTC, genryxy commented
@g4s8 please reapprove because I moved script to a separate folder and renamed file with it

2021-11-18 06:39 UTC, g4s8 requested changes
@genryxy sorry, it seems I didn't understand the what is the output file for these results. Now it looks like it was `./benchmarks/README.md`, am I right? Then it looks like a correct place for these results. In any case it'd be better to specify it as input parameter for this script: `python3 ./writeresults.py ./results/README.md` for more flexible configuration and debugging. Also, I don't see how this script will be executed, I think we need to add it as a Makefile target.

2021-11-18 06:45 UTC, genryxy commented
@g4s8 I supposed to add file `./benchmarks/results.md` which would contain only table with results. And specify a link to this table in `./benchmarks/README.md`

2021-11-18 07:12 UTC, genryxy commented
@g4s8 thanks, made as you suggested

2021-11-18 07:42 UTC, g4s8 requested changes
@genryxy please check my comment

2021-11-18 07:42 UTC, g4s8 commented on adapters/Makefile
> +write_results:
Does this target depend on another? As I understood, it requires some data to generate this report. Then we need a target for this data which depends on `run`: `write_results -> benchmark_data -> run`, where `benchmark_data` can process result data produced by `run` target

2021-11-18 09:06 UTC, genryxy commented
@g4s8 thanks, corrected. I thought at first call `run` and after that on another step call `draw_charts` stage because it looked for me like two different operations. But yes, it would be better join these stages into one to avoid duplicating code for calling these two stages.

2021-11-19 12:14 UTC, genryxy commented
@g4s8 could you please take a look

2021-11-22 12:23 UTC, genryxy commented
@g4s8 could you please check

2021-11-24 09:58 UTC, genryxy commented
@g4s8 please check

2021-11-25 14:26 UTC, g4s8 reviewed
@genryxy thanks

2021-11-25 14:29 UTC, g4s8 approved these changes

2021-11-25 14:29 UTC, merged