First part - basic performance test support
artipie/benchmarks pull request #57
Opened 2023-02-03 07:46 UTC by ChGen

First part squashed - basic performance test support: testing scripts, configs and test data.

2023-02-03 07:47 UTC, ChGen commented
Monitoring will be squashed as the next PR. 
Updated docs & old test data cleanup will follow.

2023-02-03 07:49 UTC, ChGen commented
@dgarus , please review.

2023-02-03 07:53 UTC, ChGen commented
@andpopov @Swizbiz , please review.

2023-02-03 07:57 UTC, dgarus commented
> @andpopov @Swizbiz , please review.

@ChGen Too many files!
You have to make detailed PR description and write what were done, directory structure and so on which may help do the review.

2023-02-03 08:39 UTC, Swizbiz commented
@ChGen 
I think, that we don't need push all maven files in `upload-maven-src`. Dependencies should be downloaded and this folder should be filled in compile/build stage.

2023-02-03 08:59 UTC, ChGen commented
@Swizbiz , I decided to put files set in the repository, because a lot of the maven dependencies are indirect, but I want actual files to be exactly the same all the time, so we could make comparisons between various runs and even in disconnected/restricted environments.

2023-02-03 09:16 UTC, dgarus commented
> @Swizbiz , I decided to put files set in the repository, because a lot of the maven dependencies are indirect, but I want actual files to be exactly the same all the time, so we could make comparisons between various runs and even in disconnected/restricted environments. And make it simpler/more predictable on runs too.

But we can just generate files which we need for testing, so I agree with @Swizbiz.

2023-02-03 09:26 UTC, ChGen commented
@dgarus , as I understand, dependencies may be potentially changed on the remote repositories (e.g. change latest version number or critical fix), which will make file set to be different. Local copy provides us stable test data set, which is the priority for performance tests.

2023-02-03 09:29 UTC, dgarus commented
> @dgarus , as I understand, dependencies may be potentially changed on the remote repositories (e.g. change latest version number or critical fix), which will make file set to be different. Local copy provides us stable test data set, which is the priority for performance tests.

No, I don't know cases like this. Every bug fix is in new version. But I say that we could **generate** files which we need to do tests.

2023-02-03 09:36 UTC, ChGen commented
@dgarus , maven adapter checks that files are correct and not broken, so random data files won't be enough for it. We could actually make some maven test data generator, but as a separate next step, since it will have some complexity.

2023-02-03 09:39 UTC, dgarus commented
> @dgarus , maven adapter checks that files are correct and not broken, so random data files won't be enough for it. We could actually make some maven test data generator, but as a separate next step, since it will have some complexity.

I don't think it is too hard. You can create a simple jar file with custom resource.

2023-02-03 09:48 UTC, ChGen commented
@dgarus , I will also have to generate metadata files, and in the end, it will be just repetitive upload/download of the uniform, almost the same, artifacts. But it could be useful as an extra set of tests, in addition to the current ones. This maven repository test set provides full set of artifacts of basic maven project with real metadata and jars, which is more similar to typical maven workload.

2023-02-03 10:17 UTC, ChGen commented
So, we decided that current files set should be removed and will be downloaded via maven with script, and separate issue will be created for implementing configurable maven test data generation.

2023-02-07 13:52 UTC, ChGen commented
@dgarus , please review, files set is removed and must downloaded via separate script `loadtests/prep-maven.sh`

2023-02-09 06:16 UTC, ChGen commented
@olenagerasimova , please review.

2023-02-09 08:48 UTC, olenagerasimova requested changes
@ChGen thanks, my point here - let's remove all the extra files (not used repo configs too) to keep artipie configuration as minimal and simple as possible

2023-02-09 08:48 UTC, olenagerasimova commented on loadtests/root/var/repo/_api_permissions.yaml
> +endpoints:
this file is not required and not used by artipie, let's remove it

2023-02-09 08:48 UTC, olenagerasimova commented on loadtests/root/var/repo/_permissions.yaml
> +permissions:
this one too

2023-02-09 08:48 UTC, olenagerasimova commented on loadtests/maven-repo-reset.sh
> +        "deploy"
maven repo in artipie supports just upload and download

2023-02-09 12:18 UTC, ChGen commented
@olenagerasimova , please review, I fixed review issues.

2023-02-09 13:52 UTC, olenagerasimova approved these changes
@ChGen thanks

2023-02-10 06:03 UTC, ChGen commented
@dgarus  , should we merge this?

2023-02-10 06:45 UTC, dgarus approved these changes

2023-02-10 07:47 UTC, merged