Monitoring support for the artipie
artipie/benchmarks pull request #63
Opened 2023-02-22 10:36 UTC by ChGen

Monitoring support for the artipie. 
Implementation consist of two docker-compose parts in `benchmarks/loadtests/monitoring/`:
- `server` - server part, currently deployed on `http://central.artipie.com:3000`. Contains Grafana+InfluxDB2+Telegraf.
- `client` - client part currently deployed on dedicated PC test bench under NAT network. Contains Artipie instance + Prometheus. `Prometheus` regularly collects `artipie` metrics and pushes to `server` to the `telegraf` public port.
Also documentation and scripts were updated.

2023-02-22 10:36 UTC, ChGen commented
@dgarus , please review.

2023-02-28 11:04 UTC, dgarus commented on loadtests/monitoring/server/docker-compose.yml
> +      - influxdb2
How to get influxdb2 port here?

2023-03-01 13:11 UTC, olenagerasimova requested changes
@ChGen thanks, just several comments

2023-03-01 13:11 UTC, olenagerasimova commented on loadtests/README.md
> +JFR recording for running artipie docker container could be accomplised via remote JMX connections. Both, `artipie-docker.sh` and `monitoring/client` open port `9999` for JMX connections to artipie c
accomplised  -> accomplished

2023-03-01 13:11 UTC, olenagerasimova commented on loadtests/monitoring/client/artipie/var/repo/_api_permissions.yaml
> +endpoints:
this file is not needed

2023-03-01 13:11 UTC, olenagerasimova commented on loadtests/monitoring/client/artipie/var/repo/_permissions.yaml
> +  artipie:
this file is not needed

2023-03-02 12:58 UTC, ChGen commented
@dgarus , please review, I moved InfluxDB2 port number to the variable and fixed few other issues.

2023-03-03 08:36 UTC, dgarus approved these changes

2023-03-03 13:22 UTC, Swizbiz approved these changes
@ChGen Thank you! 
LGTM

2023-03-06 06:15 UTC, ChGen commented
@olenagerasimova , please review. I fixed the issues, and GitHub requests your approval.

2023-03-06 06:25 UTC, olenagerasimova approved these changes

2023-03-06 09:31 UTC, merged