Docs updates
artipie/benchmarks pull request #74
Opened 2023-06-09 13:33 UTC by ChGen

Updated docs. Added current performance test rig documentation. Part of #64

2023-06-09 13:34 UTC, ChGen commented
@dgarus @olenagerasimova , please review.

2023-06-13 08:34 UTC, olenagerasimova requested changes
@ChGen thanks, one comment

2023-06-13 08:34 UTC, olenagerasimova commented on loadtests/perftests-setup.md
> +#### Graphs for test tags
this header seems off

2023-06-13 08:56 UTC, ChGen commented on loadtests/perftests-setup.md
> +#### Graphs for test tags
Thanks

2023-06-13 09:38 UTC, olenagerasimova approved these changes
lgtm

2023-06-13 10:10 UTC, dgarus approved these changes
lgtm

2023-06-13 11:20 UTC, merged